const africanCountries = [
  { "country": "Algeria", "capital": "Algiers", "url": "dz", "touched": false },
  { "country": "Angola", "capital": "Luanda", "url": "ao", "touched": false },
  { "country": "Benin", "capital": "Porto-Novo", "url": "bj", "touched": false },
  { "country": "Botswana", "capital": "Gaborone", "url": "bw", "touched": false },
  { "country": "Burkina Faso", "capital": "Ouagadougou", "url": "bf", "touched": false },
  { "country": "Burundi", "capital": "Bujumbura", "url": "bi", "touched": false },
  { "country": "Cabo Verde", "capital": "Praia", "url": "cv", "touched": false },
  { "country": "Cameroon", "capital": "Yaoundé", "url": "cm", "touched": false },
  { "country": "Central African Republic", "capital": "Bangui", "url": "cf", "touched": false },
  { "country": "Chad", "capital": "N'Djamena", "url": "td", "touched": false },
  { "country": "Comoros", "capital": "Moroni", "url": "km", "touched": false },
  { "country": "Congo", "capital": "Brazzaville", "url": "cg", "touched": false },
  { "country": "DR Congo", "capital": "Kinshasa", "url": "cd", "touched": false },
  { "country": "Djibouti", "capital": "Djibouti City", "url": "dj", "touched": false },
  { "country": "Egypt", "capital": "Cairo", "url": "eg", "touched": false },
  { "country": "Equatorial Guinea", "capital": "Malabo", "url": "gq", "touched": false },
  { "country": "Eritrea", "capital": "Asmara", "url": "er", "touched": false },
  { "country": "Eswatini", "capital": "Mbabane", "url": "sz", "touched": false },
  { "country": "Ethiopia", "capital": "Addis Ababa", "url": "et", "touched": false },
  { "country": "Gabon", "capital": "Libreville", "url": "ga", "touched": false },
  { "country": "Gambia", "capital": "Banjul", "url": "gm", "touched": false },
  { "country": "Ghana", "capital": "Accra", "url": "gh", "touched": false },
  { "country": "Guinea", "capital": "Conakry", "url": "gn", "touched": false },
  { "country": "Guinea-Bissau", "capital": "Bissau", "url": "gw", "touched": false },
  { "country": "Ivory Coast", "capital": "Yamoussoukro", "url": "ci", "touched": false },
  { "country": "Kenya", "capital": "Nairobi", "url": "ke", "touched": false },
  { "country": "Lesotho", "capital": "Maseru", "url": "ls", "touched": false },
  { "country": "Liberia", "capital": "Monrovia", "url": "lr", "touched": false },
  { "country": "Libya", "capital": "Tripoli", "url": "ly", "touched": false },
  { "country": "Madagascar", "capital": "Antananarivo", "url": "mg", "touched": false },
  { "country": "Malawi", "capital": "Lilongwe", "url": "mw", "touched": false },
  { "country": "Mali", "capital": "Bamako", "url": "ml", "touched": false },
  { "country": "Mauritania", "capital": "Nouakchott", "url": "mr", "touched": false },
  { "country": "Mauritius", "capital": "Port Louis", "url": "mu", "touched": false },
  { "country": "Morocco", "capital": "Rabat", "url": "ma", "touched": false },
  { "country": "Mozambique", "capital": "Maputo", "url": "mz", "touched": false },
  { "country": "Namibia", "capital": "Windhoek", "url": "na", "touched": false },
  { "country": "Niger", "capital": "Niamey", "url": "ne", "touched": false },
  { "country": "Nigeria", "capital": "Abuja", "url": "ng", "touched": false },
  { "country": "Rwanda", "capital": "Kigali", "url": "rw", "touched": false },
  { "country": "Sao Tome and Principe", "capital": "Sao Tome", "url": "st", "touched": false },
  { "country": "Senegal", "capital": "Dakar", "url": "sn", "touched": false },
  { "country": "Seychelles", "capital": "Victoria", "url": "sc", "touched": false },
  { "country": "Sierra Leone", "capital": "Freetown", "url": "sl", "touched": false },
  { "country": "Somalia", "capital": "Mogadishu", "url": "so", "touched": false },
  { "country": "South Africa", "capital": "Pretoria", "url": "za", "touched": false },
  { "country": "South Sudan", "capital": "Juba", "url": "ss", "touched": false },
  { "country": "Sudan", "capital": "Khartoum", "url": "sd", "touched": false },
  { "country": "Tanzania", "capital": "Dodoma", "url": "tz", "touched": false },
  { "country": "Togo", "capital": "Lome", "url": "tg", "touched": false },
  { "country": "Tunisia", "capital": "Tunis", "url": "tn", "touched": false },
  { "country": "Uganda", "capital": "Kampala", "url": "ug", "touched": false },
  { "country": "Zambia", "capital": "Lusaka", "url": "zm", "touched": false },
  { "country": "Zimbabwe", "capital": "Harare", "url": "zw", "touched": false }
];

export default africanCountries;
