const africanCountries = [
    { country: "Algeria", capital: "Algiers", url: "dz" },
    { country: "Angola", capital: "Luanda", url: "ao" },
    { country: "Benin", capital: "Porto-Novo", url: "bj" },
    { country: "Botswana", capital: "Gaborone", url: "bw" },
    { country: "Burkina Faso", capital: "Ouagadougou", url: "bf" },
    { country: "Burundi", capital: "Bujumbura", url: "bi" },
    { country: "Cabo Verde", capital: "Praia", url: "cv" },
    { country: "Cameroon", capital: "Yaoundé", url: "cm" },
    { country: "Central African Republic", capital: "Bangui", url: "cf" },
    { country: "Chad", capital: "N'Djamena", url: "td" },
    { country: "Comoros", capital: "Moroni", url: "km" },
    { country: "Congo (Congo-Brazzaville)", capital: "Brazzaville", url: "cg" },
    { country: "DR Congo (Congo-Kinshasa)", capital: "Kinshasa", url: "cd" },
    { country: "Djibouti", capital: "Djibouti City", url: "dj" },
    { country: "Egypt", capital: "Cairo", url: "eg" },
    { country: "Equatorial Guinea", capital: "Malabo", url: "gq" },
    { country: "Eritrea", capital: "Asmara", url: "er" },
    { country: "Eswatini", capital: "Mbabane", url: "sz" },
    { country: "Ethiopia", capital: "Addis Ababa", url: "et" },
    { country: "Gabon", capital: "Libreville", url: "ga" },
    { country: "Gambia", capital: "Banjul", url: "gm" },
    { country: "Ghana", capital: "Accra", url: "gh" },
    { country: "Guinea", capital: "Conakry", url: "gn" },
    { country: "Guinea-Bissau", capital: "Bissau", url: "gw" },
    { country: "Ivory Coast", capital: "Yamoussoukro", url: "ci" },
    { country: "Kenya", capital: "Nairobi", url: "ke" },
    { country: "Lesotho", capital: "Maseru", url: "ls" },
    { country: "Liberia", capital: "Monrovia", url: "lr" },
    { country: "Libya", capital: "Tripoli", url: "ly" },
    { country: "Madagascar", capital: "Antananarivo", url: "mg" },
    { country: "Malawi", capital: "Lilongwe", url: "mw" },
    { country: "Mali", capital: "Bamako", url: "ml" },
    { country: "Mauritania", capital: "Nouakchott", url: "mr" },
    { country: "Mauritius", capital: "Port Louis", url: "mu" },
    { country: "Morocco", capital: "Rabat", url: "ma" },
    { country: "Mozambique", capital: "Maputo", url: "mz" },
    { country: "Namibia", capital: "Windhoek", url: "na" },
    { country: "Niger", capital: "Niamey", url: "ne" },
    { country: "Nigeria", capital: "Abuja", url: "ng" },
    { country: "Rwanda", capital: "Kigali", url: "rw" },
    { country: "Sao Tome and Principe", capital: "Sao Tome", url: "st" },
    { country: "Senegal", capital: "Dakar", url: "sn" },
    { country: "Seychelles", capital: "Victoria", url: "sc" },
    { country: "Sierra Leone", capital: "Freetown", url: "sl" },
    { country: "Somalia", capital: "Mogadishu", url: "so" },
    { country: "South Africa", capital: "Pretoria (administrative), Bloemfontein (judicial), Cape Town (legislative)", url: "za" },
    { country: "South Sudan", capital: "Juba", url: "ss" },
    { country: "Sudan", capital: "Khartoum", url: "sd" },
    { country: "Tanzania", capital: "Dodoma", url: "tz" },
    { country: "Togo", capital: "Lome", url: "tg" },
    { country: "Tunisia", capital: "Tunis", url: "tn" },
    { country: "Uganda", capital: "Kampala", url: "ug" },
    { country: "Zambia", capital: "Lusaka", url: "zm" },
    { country: "Zimbabwe", capital: "Harare", url: "zw" }
  ];
  